main: main.c
	gcc graphics/paint.c main.c -o nivlem -I/usr/include/allegro5 -L/usr/lib -lallegro -lallegro_image -lallegro_primitives -lallegro_ttf -lallegro_font -lallegro_audio -lallegro_acodec -lallegro_dialog -pthread
