main: main.c
	gcc aux/list.c aux/calc.c aux/tcp_connection.c graphics/paint.c main.c -o gallinas -I/usr/include/allegro5 -L/usr/lib -lallegro -lallegro_image -lallegro_primitives -lallegro_ttf -lallegro_font -lallegro_audio -lallegro_acodec -lallegro_dialog -pthread -lm
